### ISSUE TITLE
dbdicom (record.py)

### ISSUE THREAD

**Issue by JoaoPeriquito** [QIB-Sheffield/dbdicom#7]
line 265: nr_of_slices = np.prod(array.shape[:-2])

should be replaced by nr_of_slices = **int(**np.prod(array.shape[:-2])**)**

in case of one slice "nr_of_slices" = 1.0 which is not an integer

**Comment by plaresmedima** [comment]
We need a bit more detail with an issue.

Where was this a problem? Can you add a code snippet where it crashed and
then the error message?

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JoaoPeriquito** [comment]
sure, here it is:

![image](https://user-images.githubusercontent.com/48806417/176445210-56a9a802-eeda-4cbf-8c11-e4f63bf215fd.png)

**Comment by plaresmedima** [comment]
sorted by restructure
